image: golang:latest

stages:
  - build
  - test

before_script:
  - go version
  - go mod download
  - chmod +x ./setup_env.sh
  - ./setup_env.sh

build:
  stage: build
  script:
    - go build -o todolist

test:
  stage: test
  script:
    - go test -v ./...
