image: golang:latest

stages:
  - build
  - test
  - analyze
  - deploy

before_script:
  - go version
  - go mod download

build:
  stage: build
  script:
    - go build -o todolist

test:
  stage: test
  script:
    - go test -v ./...

analyze:
  stage: analyze
  before_script:
    - apt-get update
    - apt-get install -y unzip
    - curl -sSLo /tmp/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
    - unzip /tmp/sonar-scanner.zip -d /opt
    - ln -s /opt/sonar-scanner-4.8.0.2856-linux/bin/sonar-scanner /usr/local/bin/sonar-scanner
    - go version
  script:
    - >
      sonar-scanner 
      -Dsonar.login=$SONAR_TOKEN 
      -Dsonar.host.url=$SONAR_HOST_URL 
      -Dsonar.projectKey=$SONAR_PROJECT_KEY 
      -Dsonar.language=go 
      -Dsonar.sources=. 
      -Dsonar.exclusions=**/*_test.go 
      -Dsonar.tests=. 
      -Dsonar.test.inclusions=**/*_test.go 
      -Dsonar.go.coverage.reportPaths=coverage.out
  allow_failure: true

deploy:
  stage: deploy
  before_script:
    - apt-get update
    - apt-get install -y curl
    - curl -L https://fly.io/install.sh | sh
    - ln -s /root/.fly/bin/flyctl /usr/local/bin/flyctl
  script:
    - >
      flyctl secrets set 
      DB_HOST=$DB_HOST 
      DB_USER=$DB_USER 
      DB_PASSWORD=$DB_PASSWORD 
      DB_NAME=$DB_NAME 
      DB_PORT=$DB_PORT 
    - flyctl deploy
  only:
    - staging
    - master